name = "Strongest Oppenheimen"
author = "Varg"
version = "1.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8696815e2f7a9cc256ef53ed66dc7438188d0798defe1ef901e65988a0fdb4e"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
