name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49907e80b02c65f88521534d75e2191cf1ef91136d038545c8d7053f393729a2"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
