name = "Strongest Oppenheimen"
author = "Varg"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c5e5fdd88ea4352f6a985122cc655c8d8529c2e32a83328e3ae1881bbbb112d"

[versions]
forge = "47.1.36"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
