name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efed06926edb9aee56a54aea7ad1a5b5f136257cba5770bc2da722498f563660"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
