name = "Strongest Oppenheimen"
author = "Varg"
version = "1.3.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2348552b07419c0acf9abc577dc0035bd6aa8099256f16e5fd28a6ec8f624e72"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
