name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5c18502deb652d3f0c035e3471d186467877f6124d7f760d1d24518269b0fe4"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
