name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25d08e06d0882285edce652888c00093bd408cbb8b8daaf6635fcfc209897727"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
