name = "Strongest Oppenheimen"
author = "Varg"
version = "1.3.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfe94fd1094b3384c1f5e7eb624d414e95983fde972657e44491b97023a21464"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
