name = "Strongest Oppenheimen"
author = "Varg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df041a4bbf0840eb1b7962556a3d6bd31075f2c28de2cee11d050f786828f81"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
