name = "Strongest Oppenheimen"
author = "Varg"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "614816d0ccab18cfba060d0ae71c9925d975175f05eb5fda07f31acb2ec129b7"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
