name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8105e3f5bf38f736d8bf31961d09d770278748be439959845db0588b2591562b"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
