name = "Strongest Oppenheimen"
author = "Varg"
version = "1.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b9e65947d986a8de49783c1e7ebb4125be4c31f70aaa54a6ee20afbfadf79eb"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
