name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb9619c2b00f66ef232d384de34c0b7db504f6df8030fe30930914fa2ee89dc1"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
