name = "Strongest Oppenheimen"
author = "Varg"
version = "1.4.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bd2dbe753a9051f0ee5d5f4b062102bd495d2431d61642bf3be89d9cb5ddbfd"

[versions]
forge = "47.1.1"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
